Cadastro de um novo autor.
ArthurPinheiro/dev-eficiente pull request #1
Opened 2020-01-21 20:17 UTC by ArthurPinheiro

Criação de entidade autor e operações iniciais de crud com o objeto.

2020-01-22 18:16 UTC, asouza requested changes

2020-01-22 18:16 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +    public ResponseEntity<?> listar(Pageable pageable) {
O comentário vai aqui para o método listar e editar, inicialmente. Lembra que a gente não precisa deles nesse momento, então é melhor não criarmos, tudo bem? Se quiser manter e alterar em função do que vou falar relativo ao criar em si, ok também :).

2020-01-22 18:16 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +    public ResponseEntity<?> salvar(@Valid @RequestBody Autor autor) {
*Separamos as bordas externas do sistema do seu núcleo. Não ligamos parâmetros de requisição externa com objetos de domínio diretamente, assim como não serializamos objetos de domínio para respostas de API.*

Receber o autor direto como argumento faz com que os argumentos da requisição sejam associados direto ao objeto de domínio. O problema disso é que se você mexer nesse objeto, o que pode acontecer já que ele pertence ao domínio, você pode quebrar o endpoint. Idealmente seu endpoint deveria viver sem quebrar por conta de alterações no domínio. Isso inclusive é uma otimização prematura, mas na minha experiência se mostra super válido. Você inclusive teria começado a testar o endpoint sem ter a classe autor criada :).

2020-01-22 18:16 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +        return new ResponseEntity<>(autor, HttpStatus.OK);
Mesma coisa vale aqui. Não conecta o domínio na borda nem na entrada de parâmetros e nem na saída :)

2020-01-22 18:16 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/domain/AbstractEntity.java
> +public abstract class AbstractEntity implements Serializable {
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Essa é uma prática até comum. Então precisamos fazer o exercício de imaginação e esquecer algumas das nossas verdades... Qual é a dificuldade de se criar um atributo na id na classe em si? Nesse momento aqui você introduziu heranca. annotation um pouco mais complicada do hibernate, sem contar o uso do lombok. A pergunta para o lombok é: como realmente o lombok funciona? Como que os getters e setters são gerados? Se a pessoa  não sabe disso ela vai começar a refletir sobre isso para procurar respostas.. enquanto isso ela vai ser menos produtiva...

2020-01-22 18:16 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/domain/AbstractEntity.java
> +public abstract class AbstractEntity implements Serializable {
Recomendo apagar essa classe

2020-01-22 18:16 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/domain/Autor.java
> +public class Autor extends AbstractEntity {
Já comentei do lombok e da AbstractEntity.. Mas olha bem para essas annotations.. Tem mais annotation do que código :). Mais algumas coisas..

* Gerar o construtor com a data permite que alguém crie o objeto indicando uma data de criação diferente da atual
* Para que queremos um builder se já temos um construtor que recebe apenas 2 argumentos?
* A necessidade do getter e setter veio por conta de receber o parâmetro conectado lá no controller. Não precisamos, neste momento, nem pegar info do autor nem alterar parcialmente.
* Também não precisamos de um construtor sem argumentos.

2020-01-23 02:23 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +    public ResponseEntity<?> listar(Pageable pageable) {
Certo, entendi.

2020-01-23 02:27 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/domain/AbstractEntity.java
> +public abstract class AbstractEntity implements Serializable {
Na começo da criação do projeto, tive dúvidas se criaria cada classe separada ou usuária um classe abstrata para herdar o id, ou outros atributos que fossem em comum. O uso do lombok é mais para "limpeza de código", para ter não que criar getter e setters para todos.

2020-01-23 02:28 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/domain/Autor.java
> +public class Autor extends AbstractEntity {
Sim, o builder é bom para quando temos vários atributos dentro de uma mesma classe, de fato está errado. Entendi as outras obs.

2020-01-23 02:29 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +    public ResponseEntity<?> salvar(@Valid @RequestBody Autor autor) {
Entendi parcialmente. Vou procurar consertar e subir junto com as outras alterações.

2020-01-23 02:31 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/domain/AbstractEntity.java
> +public abstract class AbstractEntity implements Serializable {
Entendo. Sobre o lombok, ok. Realmente não acho que limpa, pelo contrário. Você escreve a mesma coisa de uma forma diferente da habitual e sem um ganho real... Já que não tem muita diferença de tempo entre escrever a annotation e gerar automático as coisas pela ide. 

Sobre a classe mãe em si, essa realmente só complica sua vida. Você faz um mapeamento do hibernate mais complicado, deixa o domínio mais complicado pq todo mundo vai herdar explicitamente de uma classe e nada disso traz alguma vantagem para o código em si.

2020-01-23 02:33 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +    public ResponseEntity<?> salvar(@Valid @RequestBody Autor autor) {
Dá uma olhada neste vídeo aqui => https://www.youtube.com/watch?v=lq5xpz79i5Q&list=PLVHlvMRWE0Y70QZLWvQvDxxQtFeOEHFkY&index=5&t=726s

2020-01-23 02:33 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/domain/AbstractEntity.java
> +public abstract class AbstractEntity implements Serializable {
Beleza, entendido !!

2020-01-23 03:25 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/controller/AutorController.java
> +    public ResponseEntity<?> salvar(@Valid @RequestBody Autor autor) {
Massa! Não tinha visto, nem pensado dessa forma. Sempre os exemplos que vi foi passando o objeto todo, no meu trabalho tbm é dessa forma ( a gente trabalha com vraptor). Verei os outros vídeos do canal. Valeeu !!

2020-01-25 01:18 UTC, ArthurPinheiro reviewed
@asouza por favor, revisar.

2020-01-25 02:49 UTC, asouza approved these changes
Para mim ficou quase ótimo. Só a geração dos getters e setters que eu sugiro remover.

2020-01-25 02:49 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/domain/Autor.java
> +    public Long getId() {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Ainda não precisamos dos getters e setters :).

2020-01-25 02:49 UTC, asouza commented on src/main/java/com/deveficiente/casadocodigo/domain/Autor.java
> +    public void setInstante(LocalDateTime instante) {
inclusive esse setter permite que o instante da criação seja alterado.

2020-01-25 03:18 UTC, ArthurPinheiro commented on src/main/java/com/deveficiente/casadocodigo/domain/Autor.java
> +    public Long getId() {
Verdade. Sempre tenho esse questionamento quanto aos getters e setters.

2020-01-25 03:21 UTC, ArthurPinheiro commented
> Para mim ficou quase ótimo. Só a geração dos getters e setters que eu sugiro remover.

Correção feita.

2020-01-25 16:22 UTC, ArthurPinheiro commented
* Nessa implementação, pude pensar de uma forma diferente, principalmente em relação aos objetos de domínio e a proteção das bordas do sistema. Uma melhor forma de garantir a segurança para a aplicação.  

* Além disso, ter um maior senso crítico com o código que estou criando. Ter um código simples, que funcione e legível. Não querer "inventar" lógicas que podem funcionar, mas são complexas demais para o que é pedido. E sempre observar se o método que foi criado está sendo usado, se não estiver não se faz necessário.

2020-01-25 16:24 UTC, merged